version: "3.9"
services:
  common:
    image: micro/common
    build:
      context: .
      dockerfile: ./common/Dockerfile
    ports:
      - "8081:8080"
  test:
    image: micro/test
    build:
      context: .
      dockerfile: ./test/Dockerfile
    ports:
      - "8082:8080"
